-- ============================================================
-- 011: AI DRAFTS
-- Journal entry drafts generated by mnemosine (AI). The AI only
-- writes here; turning a draft into a journal_entry requires human
-- review (mnemosine review), which posts via the existing accounting
-- engine with all its validations.
-- ============================================================

CREATE TABLE ai_drafts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL,
    entity_id UUID NOT NULL REFERENCES legal_entities(id),
    draft_type VARCHAR(50) NOT NULL DEFAULT 'journal_entry'
        CHECK (draft_type IN ('journal_entry')),
    status VARCHAR(50) NOT NULL DEFAULT 'pending_review'
        CHECK (status IN ('pending_review', 'approved', 'rejected')),

    -- Full journal entry proposal:
    -- { entry_date, description, reference?, lines: [{account_code, debit?, credit?, description?}] }
    payload JSONB NOT NULL,

    -- AI decision metadata (audit)
    ai_confidence NUMERIC(3,2) NOT NULL
        CHECK (ai_confidence >= 0 AND ai_confidence <= 1),
    ai_reasoning TEXT NOT NULL,
    ai_model VARCHAR(100) NOT NULL,
    user_request TEXT,

    -- Human review outcome
    journal_entry_id UUID REFERENCES journal_entries(id),
    review_notes TEXT,
    reviewed_by VARCHAR(255),
    reviewed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255) NOT NULL DEFAULT 'mnemosine-cli',

    -- An approved draft always points to the journal entry it generated
    CHECK (status != 'approved' OR journal_entry_id IS NOT NULL)
);

CREATE INDEX idx_ai_drafts_entity_status ON ai_drafts(entity_id, status);
CREATE INDEX idx_ai_drafts_tenant ON ai_drafts(tenant_id);
