import * as fs from 'node:fs';
import type { Criterio, Mutante } from './criteria/shared.js';
import { rutaDe } from './criteria/shared.js';

// ============================================================
// THE MUTATION CENSUS (#356).
//
// `criteria-mutation-harness` used to guard the mirrors with two exact
// literals, MIRRORS_FLOOR and ANCHORS_HERE, that every PR adding a mirror
// edited by hand. Two such PRs always collided on the same line, and neither
// side of the conflict was right: the right value was the sum, re-measured by
// hand (#272, #286, #346, #249).
//
// The census replaces the two numbers with ONE LINE PER MIRROR AND PER ANCHOR,
// generated from the tree and committed. It keeps what the literals protected
// —a mirror or an anchor that disappears turns CI red, and now the failure
// NAMES it— and drops what made them collide: there is no total to edit. Two
// PRs that add mirrors to different criteria add lines in different places of
// the file, so git merges them; when they do touch the same spot, the
// conflict is resolved by regenerating, never by summing.
//
// Lines follow SOURCE order (criteria in board order, anchors in file order)
// and not alphabetical order, so the census merges the way its sources merge.
// ============================================================

/** Where the committed census lives, relative to the repository root. */
export const CENSUS_FILE = 'src/plan/mutation-census.txt';

const HEADER = [
  '# Mutation census (#356). GENERATED by scripts/mutation-census.ts: do not edit by hand.',
  '# One line per mirror and per `de:` anchor. After adding or removing one, or after a',
  '# merge, regenerate with `npm run mutation:census`; CI checks it (tests/plan/mutation-census.spec.ts).',
];

/** Anchor lines, with the same pattern ANCHORS_HERE used to count. */
const ANCHOR = /^[ \t]*de: .*$/gm;

const oneLine = (s: string): string => s.replace(/\s+/g, ' ').trim();

/**
 * The files the mirror harness is made of: the index plus every package file
 * of `src/plan/criteria/`, listed from the directory so a new package file
 * cannot be left out of the count by not being named here.
 */
export function instrumentFiles(): string[] {
  return [
    'src/plan/criterios.ts',
    ...fs
      .readdirSync(rutaDe('src/plan/criteria'))
      .filter((f) => f.endsWith('.ts'))
      .sort()
      .map((f) => `src/plan/criteria/${f}`),
  ];
}

/** The census entries of one criterion's mirrors, in declaration order. */
export function mirrorEntries(criteria: readonly Criterio[]): string[] {
  return criteria.flatMap((c) => {
    const who = `${c.paquete} ${c.id ?? oneLine(c.enunciado)}`;
    const line = (kind: string) => (m: Mutante) =>
      `mirror\t${kind}\t${who}\t${m.archivo}\t${oneLine(m.porque)}`;
    return [...(c.mutantes ?? []).map(line('memory')), ...(c.mutantesEnDisco ?? []).map(line('disk'))];
  });
}

/** The census entries of the `de:` anchors written in one instrument file. */
export function anchorEntries(file: string, source: string): string[] {
  return (source.match(ANCHOR) ?? []).map((l) => `anchor\t${file}\t${oneLine(l)}`);
}

/** The whole census, measured on the tree that `read` sees. */
export function measureCensus(
  criteria: readonly Criterio[],
  files: readonly string[],
  read: (file: string) => string
): string[] {
  return [...mirrorEntries(criteria), ...files.flatMap((f) => anchorEntries(f, read(f)))];
}

export function renderCensus(entries: readonly string[]): string {
  return [...HEADER, ...entries].join('\n') + '\n';
}

export function parseCensus(text: string): string[] {
  return text.split('\n').filter((l) => l.trim() !== '' && !l.startsWith('#'));
}

/**
 * What one side has that the other lacks, as a multiset: two identical
 * mirrors are two lines, and losing one of them is a loss.
 */
export function missingFrom(expected: readonly string[], actual: readonly string[]): string[] {
  const left = new Map<string, number>();
  for (const e of actual) left.set(e, (left.get(e) ?? 0) + 1);
  const missing: string[] = [];
  for (const e of expected) {
    const n = left.get(e) ?? 0;
    if (n > 0) left.set(e, n - 1);
    else missing.push(e);
  }
  return missing;
}

export interface CensusDrift {
  /** In the committed census, gone from the tree: a mirror or anchor was retired. */
  vanished: string[];
  /** In the tree, not yet in the committed census: it needs regenerating. */
  unrecorded: string[];
}

export function censusDrift(committed: readonly string[], live: readonly string[]): CensusDrift {
  return { vanished: missingFrom(committed, live), unrecorded: missingFrom(live, committed) };
}

/** A census entry as a person reads it in a failure message. */
export function describeEntry(entry: string): string {
  const [kind, ...rest] = entry.split('\t');
  return kind === 'mirror'
    ? `mirror (${rest[0]}) of ${rest[1]} on ${rest[2]}: ${rest[3]}`
    : `anchor in ${rest[0]}: ${rest[1]}`;
}
